command: ["streamlit", "run", "app/app.py"]

env:
  - name: DOC_INTEL_CONFIG
    value: configs/wsp.yaml
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
